package com.timi.timizhuo.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.timi.timizhuo.entity.TimiImages;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TimiImagesMapper extends BaseMapper<TimiImages> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_images
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_images
     *
     * @mbg.generated
     */
    int insert(TimiImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_images
     *
     * @mbg.generated
     */
    int insertSelective(TimiImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_images
     *
     * @mbg.generated
     */
    TimiImages selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_images
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TimiImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_images
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TimiImages record);

    List<TimiImages> findByColumnNo(@Param("columnNo") String columnNo);
}