package com.timi.timizhuo.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.timi.timizhuo.entity.TimiUserRecord;

import java.util.List;

public interface TimiUserRecordMapper extends BaseMapper<TimiUserRecord> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user_record
     *
     * @mbg.generated
     */
    int insert(TimiUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user_record
     *
     * @mbg.generated
     */
    int insertSelective(TimiUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user_record
     *
     * @mbg.generated
     */
    TimiUserRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TimiUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TimiUserRecord record);

    List<TimiUserRecord> selectByUsername(String username);
}