package com.timi.timizhuo.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.timi.timizhuo.entity.TimiUser;

public interface TimiUserMapper extends BaseMapper<TimiUser> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user
     *
     * @mbg.generated
     */
    int insert(TimiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user
     *
     * @mbg.generated
     */
    int insertSelective(TimiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user
     *
     * @mbg.generated
     */
    TimiUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TimiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TimiUser record);

    TimiUser selectByUsernameAndPassword(TimiUser timiUser);

    TimiUser selectByUsername(String username);

    TimiUser selectByNickname(String nickname);
}