package com.timi.timizhuo.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.timi.timizhuo.entity.TimiColumn;

import java.util.List;

public interface TimiColumnMapper extends BaseMapper<TimiColumn> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    int insert(TimiColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    int insertSelective(TimiColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    TimiColumn selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TimiColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TimiColumn record);

    List<TimiColumn> findByCondition(TimiColumn timiColumn);

    TimiColumn findByColumnNo(String columnNo);
}