package com.timi.timizhuo.entity;

import com.baomidou.mybatisplus.annotation.TableField;
import lombok.Data;

import java.util.Date;

@Data
public class TimiColumn extends BaseEntity {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_column.column_no
     *
     * @mbg.generated
     */
    private String columnNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_column.column_name
     *
     * @mbg.generated
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_column.column_type
     *
     * @mbg.generated
     */
    private String columnType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_column.parent_column
     *
     * @mbg.generated
     */
    private String parentColumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_column.column_time
     *
     * @mbg.generated
     */
    private Date columnTime;

    @TableField(exist = false)
    private long columnTimeLong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

}