package com.timi.timizhuo.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class TimiColumn implements Serializable {

    @TableId(type = IdType.UUID)
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_column.column_no
     *
     * @mbg.generated
     */
    private String columnNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_column.column_name
     *
     * @mbg.generated
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_column.column_type
     *
     * @mbg.generated
     */
    private String columnType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_column.parent_column
     *
     * @mbg.generated
     */
    private String parentColumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_column.column_time
     *
     * @mbg.generated
     */
    private Date columnTime;

    private long columnTimeLong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_column.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_column.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", columnNo=").append(columnNo);
        sb.append(", columnName=").append(columnName);
        sb.append(", columnType=").append(columnType);
        sb.append(", parentColumn=").append(parentColumn);
        sb.append(", columnTime=").append(columnTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}