package com.timi.timizhuo.entity;

import lombok.Data;

import java.util.Date;

@Data
public class TimiImages extends BaseEntity {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_images.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    private String thumbnailUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_images.alt
     *
     * @mbg.generated
     */
    private String alt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_images.column_no
     *
     * @mbg.generated
     */
    private String columnNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_images.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_images.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table timi_images
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

}