package com.timi.timizhuo.dao.model;

import java.io.Serializable;
import java.util.Date;

public class TimiVideo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_video.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_video.video_title
     *
     * @mbg.generated
     */
    private String videoTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_video.video_cover
     *
     * @mbg.generated
     */
    private String videoCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_video.video_content_url
     *
     * @mbg.generated
     */
    private String videoContentUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_video.video_time
     *
     * @mbg.generated
     */
    private String videoTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_video.love_count
     *
     * @mbg.generated
     */
    private Long loveCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_video.show_count
     *
     * @mbg.generated
     */
    private Long showCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_video.collection_count
     *
     * @mbg.generated
     */
    private Long collectionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_video.column_no
     *
     * @mbg.generated
     */
    private String columnNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_video.column_name
     *
     * @mbg.generated
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_video.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_video.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table timi_video
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timi_video.id
     *
     * @return the value of timi_video.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timi_video.id
     *
     * @param id the value for timi_video.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timi_video.video_title
     *
     * @return the value of timi_video.video_title
     *
     * @mbg.generated
     */
    public String getVideoTitle() {
        return videoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timi_video.video_title
     *
     * @param videoTitle the value for timi_video.video_title
     *
     * @mbg.generated
     */
    public void setVideoTitle(String videoTitle) {
        this.videoTitle = videoTitle == null ? null : videoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timi_video.video_cover
     *
     * @return the value of timi_video.video_cover
     *
     * @mbg.generated
     */
    public String getVideoCover() {
        return videoCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timi_video.video_cover
     *
     * @param videoCover the value for timi_video.video_cover
     *
     * @mbg.generated
     */
    public void setVideoCover(String videoCover) {
        this.videoCover = videoCover == null ? null : videoCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timi_video.video_content_url
     *
     * @return the value of timi_video.video_content_url
     *
     * @mbg.generated
     */
    public String getVideoContentUrl() {
        return videoContentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timi_video.video_content_url
     *
     * @param videoContentUrl the value for timi_video.video_content_url
     *
     * @mbg.generated
     */
    public void setVideoContentUrl(String videoContentUrl) {
        this.videoContentUrl = videoContentUrl == null ? null : videoContentUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timi_video.video_time
     *
     * @return the value of timi_video.video_time
     *
     * @mbg.generated
     */
    public String getVideoTime() {
        return videoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timi_video.video_time
     *
     * @param videoTime the value for timi_video.video_time
     *
     * @mbg.generated
     */
    public void setVideoTime(String videoTime) {
        this.videoTime = videoTime == null ? null : videoTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timi_video.love_count
     *
     * @return the value of timi_video.love_count
     *
     * @mbg.generated
     */
    public Long getLoveCount() {
        return loveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timi_video.love_count
     *
     * @param loveCount the value for timi_video.love_count
     *
     * @mbg.generated
     */
    public void setLoveCount(Long loveCount) {
        this.loveCount = loveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timi_video.show_count
     *
     * @return the value of timi_video.show_count
     *
     * @mbg.generated
     */
    public Long getShowCount() {
        return showCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timi_video.show_count
     *
     * @param showCount the value for timi_video.show_count
     *
     * @mbg.generated
     */
    public void setShowCount(Long showCount) {
        this.showCount = showCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timi_video.collection_count
     *
     * @return the value of timi_video.collection_count
     *
     * @mbg.generated
     */
    public Long getCollectionCount() {
        return collectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timi_video.collection_count
     *
     * @param collectionCount the value for timi_video.collection_count
     *
     * @mbg.generated
     */
    public void setCollectionCount(Long collectionCount) {
        this.collectionCount = collectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timi_video.column_no
     *
     * @return the value of timi_video.column_no
     *
     * @mbg.generated
     */
    public String getColumnNo() {
        return columnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timi_video.column_no
     *
     * @param columnNo the value for timi_video.column_no
     *
     * @mbg.generated
     */
    public void setColumnNo(String columnNo) {
        this.columnNo = columnNo == null ? null : columnNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timi_video.column_name
     *
     * @return the value of timi_video.column_name
     *
     * @mbg.generated
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timi_video.column_name
     *
     * @param columnName the value for timi_video.column_name
     *
     * @mbg.generated
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timi_video.create_time
     *
     * @return the value of timi_video.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timi_video.create_time
     *
     * @param createTime the value for timi_video.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timi_video.update_time
     *
     * @return the value of timi_video.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timi_video.update_time
     *
     * @param updateTime the value for timi_video.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_video
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", videoTitle=").append(videoTitle);
        sb.append(", videoCover=").append(videoCover);
        sb.append(", videoContentUrl=").append(videoContentUrl);
        sb.append(", videoTime=").append(videoTime);
        sb.append(", loveCount=").append(loveCount);
        sb.append(", showCount=").append(showCount);
        sb.append(", collectionCount=").append(collectionCount);
        sb.append(", columnNo=").append(columnNo);
        sb.append(", columnName=").append(columnName);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}