package com.timi.timizhuo.dto;

import lombok.Data;

import java.util.Date;

/**
 * @Description 卓依婷视频栏目实体传输类
 * @Auther timi
 * @Date 2018/12/2 000213:54
 */
@Data
public class TimiColumnDto extends BaseDto {

    private String id;

    private String columnNo;

    private String columnName;

    private String columnType;

    private String parentColumn;

    private Date columnTime;

    private long columnTimeLong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timi_column.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    private Date updateTime;

    private static final long serialVersionUID = 1L;

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", columnNo=").append(columnNo);
        sb.append(", columnName=").append(columnName);
        sb.append(", columnType=").append(columnType);
        sb.append(", parentColumn=").append(parentColumn);
        sb.append(", columnTime=").append(columnTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
