package com.timi.timizhuo.dao.mapper;

import com.timi.timizhuo.dao.model.TimiVideo;

import java.util.List;

public interface TimiVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_video
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_video
     *
     * @mbg.generated
     */
    int insert(TimiVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_video
     *
     * @mbg.generated
     */
    int insertSelective(TimiVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_video
     *
     * @mbg.generated
     */
    TimiVideo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_video
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TimiVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_video
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TimiVideo record);

    List<TimiVideo> findByCondition(TimiVideo timiVideo);
}