package com.timi.timizhuo.dao.mapper;

import com.timi.timizhuo.dao.model.TimiVideoComment;

public interface TimiVideoCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_video_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_video_comment
     *
     * @mbg.generated
     */
    int insert(TimiVideoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_video_comment
     *
     * @mbg.generated
     */
    int insertSelective(TimiVideoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_video_comment
     *
     * @mbg.generated
     */
    TimiVideoComment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_video_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TimiVideoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_video_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TimiVideoComment record);
}