package com.timi.timizhuo.dao.mapper;

import com.timi.timizhuo.dao.model.TimiUserRecord;

import java.util.List;

public interface TimiUserRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user_record
     *
     * @mbg.generated
     */
    int insert(TimiUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user_record
     *
     * @mbg.generated
     */
    int insertSelective(TimiUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user_record
     *
     * @mbg.generated
     */
    TimiUserRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TimiUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_user_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TimiUserRecord record);

    List<TimiUserRecord> selectByUsername(String username);
}