package com.timi.timizhuo.dao.mapper;

import com.timi.timizhuo.dao.model.TimiColumn;

import java.util.List;

public interface TimiColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    int insert(TimiColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    int insertSelective(TimiColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    TimiColumn selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TimiColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timi_column
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TimiColumn record);

    List<TimiColumn> findByCondition(TimiColumn timiColumn);

    TimiColumn findByColumnNo(String columnNo);
}